src/App.js
Signed-off-by: Esteban Rocha <esteban@rocha.codes>
=> Adds PHP and corrects WP date as zero index months

src/App.js
Couldn't find a day but Wikipedia and [Cake's Docs](https://book.cakephp.org/1.1/en/introduction-to-cakephp.html#history-of-cakephp) list the first launch around April 2005.
=> Adding CakePhp To List.

src/App.js
https://github.com/tensorflow/tensorflow/releases
=> Adds Tensorflow

src/App.js
https://en.wikipedia.org/wiki/PyTorch Stable Release Date
=> Adds PyTorch

src/App.js
Based on first appearance: https://en.wikipedia.org/wiki/Haskell_(programming_language)
=> Add Haskell to the list of languages

src/App.js
I find it ridiculous that recruiters require that you have 65 years experience of Fortran, when it's only been out for 62 years.
=> Add Fortran to the list of languages.

src/App.js
Little tip : Laravel versions before 4 are really outdated and nobody work on it, version 4 is still usable but the version 5 is widely adopted as by now because there was a major rewrite between the version 4 to 5, to made it really simple to develop with.
=> Laravel subtilities

src/App.js
=> Add Android release

src/App.js
Source: https://en.wikipedia.org/wiki/Cascading_Style_Sheets
=> Add CSS release

src/App.js
Source https://en.wikipedia.org/wiki/Xamarin
=> Add Xamarin Forms

src/technologies.js
The implementation of Lisp started in the fall of 1958.
http://www-formal.stanford.edu/jmc/history/lisp/lisp.html
=> Add Lisp to technologies

src/App.css
=> update input style

src/technologies.js
Added [Polymer](https://www.polymer-project.org/) library.
=> Add polymer

README.md
Changes to readme.md to make it easier for new contributors to start contributing to the repository.
=> Changes to the readme.md

src/technologies.js
Brainfuck : https://esolangs.org/wiki/brainfuck
Julia : https://julialang.org/
=> Add Brainfuck and Julia

src/technologies.js
Add AdonisJs: a brand new framework which become popular!
https://github.com/adonisjs
https://adonisjs.com/
=> Add AdonisJs in technologies list

src/technologies.js
=> Fixed Magento release date

src/technologies.js
Really great concept. :) I added SQLite.
=> Add SQLite

src/technologies.js
I wanted them to be by the other N technologies, but then they'd fail the 'is sorted by name' test.
=> Added in .NET technologies

src/technologies.js
Creation date based on Wikipedia:
https://en.wikipedia.org/wiki/Markdown
=> Added markdown

src/technologies.js
=> update jenkins to take hudson into consideration

src/technologies.js
Add Cassandra database technology
http://cassandra.apache.org/
=> Add cassandra

src/technologies.js
Add Serveless framework
https://serverless.com/
=> Add Serveless framework

src/technologies.js
=> added Logo

src/technologies.js
Firebase is a mobile and web application development platform developed by Firebase, Inc. in 2011, Launched in 2012 and then acquired by Google in 2014.
[https://firebase.google.com/](https://firebase.google.com/)
=> Add Firebase

src/technologies.js
Add Phoenix Framework to technologies.js
=> Add Phoenix Framework

src/technologies.js
Add Corona game engine
https://coronalabs.com/
=> Add corona game engine

src/App.css, src/App.js
Added sorting by Tech and Age ascending and descending.
Used a href # in order to display options.
The styling should be improved, does the job but looks ... well not perfect.
Maybe this can be used as an first PoC.
Please feel free to improve the logic, currently it uses strings and is very basic.
=> Added basic sorting

src/technologies.js
=> Update .NET technologies date format

src/App.js
example link: `howoldisit.glitch.me/#react`
=> make filtered results shareable by including the filter in the url hash

src/technologies.js
Official website : http://wiki.portal.chalmers.se/agda
=> Add Agda programming language

src/technologies.js
https://en.wikipedia.org/wiki/Symfony
=> Fixed symfony age

src/technologies.js
This PR adds the following robotics technologies:
- ROS (Robotic Operating System)
- ROS2 (Robotic Operating System 2)
- PX4 Firmware (Widely adopted drone autopilot)
- Mavros (Compatibility layer for PX4 Firmware for ROS)
=> Addding some open-source robotics technologies

README.md, src/technologies.js
=> Add iOS to the list of technologies.

package.json
Useful to get references to your code, like the screenshot below.
=> Added types for jest

src/technologies.js
JavaScript is officially managed by Mozilla Foundation.
=> Added Mozilla as Javascript site

src/technologies.test.js
technologies.js is changed by all the people so we'd better test it more thoroughly.
* added logging to isSortedByName to be more verbose about where to look for an error
* added testing for requred fields 'name' and 'released'
=> Improved technologies.test.js

src/technologies.js
Just added CoffeeScript to the technologies, date is taken from its Wiki page
=> Add CoffeeScript to src/technologies.js

src/technologies.js
Added Microsoft's Windows Subsystem for Linux to technologies.js. Uses the already provided `windows` icon as assigned icon.
The date is based on the Windows 10 1607 Anniversary Update release date with which the initial functionality of WSL was introduced.
=> Added WSL to technologies.

src/technologies.js
Just adding some old tech to the list.
-nateonmission
=> Added Telnet birthdate and link to RFC15

src/technologies.js
Add Delphi, Prolog and Mithril.js to the technologies!
=> Add Delphi, Prolog and Mithril.js

src/technologies.js
=> Add Umbrella JS

src/technologies.js
Added WebdriverIO, a next-gen WebDriver test automation framework for Node.js
=> Added WebdriverIO

src/App.css
I suggest fixing the navigation bar because it is easier to search.
=> Refactor header style

src/technologies.js
Added DITA-OT, a publishing engine for XML content authored in the Darwin Information Typing Architecture(DITA).
=> Added DITA-OT

src/technologies.js
src: [https://en.wikipedia.org/wiki/Odoo](https://en.wikipedia.org/wiki/Odoo) (see "Initial release")
=> Add Odoo to technologies

src/technologies.js
=> Add podman to technologies

src/technologies.js
=> Add bootstrap (in its first version) to technologies

src/technologies.js
Source https://en.wikipedia.org/wiki/ClickHouse
=> Add ClickHouse

technologies.json
as per OG repo initial release info https://github.com/facebook/react-native/tree/v0.1.0 + https://github.com/facebook/react-native/releases?page=19
=> updated react native

technologies.json
Thought this might be worth adding :)
=> Add Capacitor
